config/routes.rb
  Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles
  resources :profiles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50} 
  validates :description, presence: true, length: {minimum: 10, maximum: 300} 
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category 
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: {minimum: 3, maximum: 25 }
            VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  def new
    @article = Article.new
  end
  
  def edit
   
  end
  
  def update
    
    if @article.update(article_params)
      flash[:primary]= "Article was successfully edited"
      redirect_to article_path(@article)
    
    else
      render 'edit'
    end
  end
  
  def create
    @article= Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    
    else
      render 'new'
    end
  end
  
  def show
   
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was sucessfully deleted"
    redirect_to articles_path
  end
  
  
  private
  def set_article
    @article = Article.find(params[:id])
  end
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  
  def new
    @profile = Profile.new
  end
  
  def create
   @profile= Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      flash[:success] = "Profile was successfully created"
      redirect_to article_path(@profile)
    
    else
      render 'new'
    end
  end  
  
  def edit
    
  end
  
private
  def set_profile
    @profile = Profile.find(params[:id])
  end
    def profile_params
      params.require(:profile).permit(:skype, :whatsapp, :language)
    end
    
    def require_same_user
      if current_user != @profile.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own profile"
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "You are logged in"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user, only: [:edit, :update, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
    def edit
    
    end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user= User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by the users have been deleted"
    redirect_to users_path
  end
    
  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
    redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "only admin users can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="card margintop">
  <div class="card-header"> <%=link_to article.title, article_path(article) %>
  </div>
    <div class="card-body">
      <h5 class="card-title">Description:</h5>
      <p class="card-text"><%= article.description %></p>
      <div>
      <small>Created by: <%= article.user.username if article.user%>,
      <%= time_ago_in_words(article.created_at) %> ago,
      last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete the article?"},
                                      class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  
</div>
<% end %>



  

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class='form'>
  <div class='col-xs-12'>
    <%= form_for(@article,:html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :title %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus:true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :Description %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :description, rows:6, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
      <div class="form-group row">
        <div class="col-sm-10  col-sm-offset-2">
          <%= f.submit class:"btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4 center">
       [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<br/><h1 align="center">Edit article</h1><br/>

<%= render 'form' %>

<%= link_to "All articles", articles_path %>

app/views/articles/index.html.erb
<div>
  <h1 class="float-left">Listing all articles</h1>
  <%= link_to "New article",new_article_path,class:"btn btn-success btn-lg float-right" %>
</div></br></br></br>
<div align="left">
  <%= will_paginate %>
</div>
<%= render 'article',obj: @articles %>
<div align="center">
  <%= will_paginate class:"pagination" %>
</div>

app/views/articles/new.html.erb
<br/><h1 align="center">Create an article</h1><br/>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="card margintop">
  <div class="card-header"> <%= @article.title %>
  </div>
    <div class="card-body">
      <% if @article.user %>
        <div class= "col">
        <span><h5><%= link_to gravatar_for(@article.user), user_path(@article.user) %></h5>
          <p>
          <%= link_to @article.user.username, user_path(@article.user) %> |
          <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
          </p>
        </span>
        </div>
    <% end %>
      <h5 class="card-title">Description:</h5>
      <p class="card-text"><%= @article.description %></p>
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"},class: "btn btn-xs btn-danger" %>
          <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
        </div>
      <% end %>
    </div>
</div>
  
  

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
  <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  <% end %>
  <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
  </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <div class="card" style="width: 18rem; margin-top:15px;">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "#{category.name}", category_path(category) %></h5>
        <small><%= pluralize(category.articles.count, "article") %></small>
      </div>
    </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="Left" class="col-sm-8">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
  <div align="center">
    <%= will_paginate @category_articles %>
  </div>
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
  <% end %>
  <%= render 'articles/article', obj: @category_articles %>
  <div align="center">
    <%= will_paginate @category_articles %>
  </div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright @copy; <a href="https://www.5roots.mx">5 Roots website</a>
        by <a href="https://www.prentige.com">Prentige</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="alert">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>' role="alert">
      <%= msg %> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span>
      </button>  
    <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top ">
    <%=link_to "5 Roots",root_path, class:"d-inline-block align-top", id:"logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if logged_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%=link_to "Articles", articles_path,class:"nav-link"%></li>
        <li class="nav-item"><%=link_to "Users", users_path,class:"nav-link"%></li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path,class:"dropdown-item" %>
          <% Category.all.each do |category| %>
          <%= link_to "#{category.name} |#{category.articles.count}|"  , category_path(category),class:"dropdown-item" %>
            <% end %>
          <% if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
          <%= link_to "Create New Category", new_category_path, class:"dropdown-item" %></li>
          <% end %>
        </div>
      </li>
    </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <span class= "nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My profile <%= "/Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit your profile", edit_user_path(current_user),class:"dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user),class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", logout_path,method: :delete,class:"dropdown-item" %>
          </div>
      </span>
      <% else %>
        <span class="navbar-nav collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item"><%= link_to 'Log in', login_path,class:"nav-link" %> </li>
          <li class="nav-item"><%= link_to 'Sign up', signup_path,class:"nav-link" %> </li>
      <% end %>
        </span>
      
    </div>
  </nav>







 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class = 'container'>
    <%= yield %>
  </div>
  <%= render'layouts/footer' %>
  <pre>>
  
  
  
  <%= debug(params) if Rails.env.development? %></pre
</body>
</html>

app/views/pages/about.html.erb
<h1>this is about</h1>

<%= link_to "Go to the home page", root_path %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to 5 roots</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to "Sign up now",signup_path, class:"btn btn-success btn-lg btn-xlarge" %> 
</div>

app/views/profiles/new.html.erb
<%= render 'shared/errors', obj: @profile %>
<div class='form'>
  <div class='col-xs-12'>
    <%= form_for(@profile,:html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :skype %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :skype, class: "form-control", placeholder: "Enter your skype id or e-mail", autofocus:true %>
        </div>
      </div>
       <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :whatsapp %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :whatsapp, class: "form-control", placeholder: "Enter your whatsapp", autofocus:true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :Timezone %>
        </div>
        <div class="col-sm-10">
          <%= time_zone_select(:person, :time_zone)  %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">Select your language</label>
        </div>
        <div class="col-sm-10">
          
          <%= select_tag(:languages, options_for_select([['English'], ['Spanish'],
                        ['Portuguese'],['Chinese'],['Italian'],['Russian'],['French']])) %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">Select the reason for learning a language</label>
        </div>
        <div class="col-sm-10">
          
          <%= select_tag(:languages, options_for_select([['School'], ['Work'],
                        ['Hobby'],['Travel'],['I am moving to other country'],['Other']])) %>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">¿When is your birthday?</label>
        </div>
        <div class="col-sm-10">
        <%= date_select :age, :birth_date %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">Select your level</label>
        </div>
        <div class="col-sm-10">
          <%= select_tag(:level, options_for_select([['0'], ['1'],
                        ['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9'],['10']])) %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">When would you like to start with your lessons</label>
        </div>
        <div class="col-sm-10">
          <%= select_tag(:begin, options_for_select([['today'], ['In a few days'],
                        ['In two weeks'],['This month']])) %>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <label for="exampleFormControlSelect1">Select 3 options for your schedule</label>
        </div>
        <div class="col-sm-10"> Primera opción
          <%= select_tag(:schedule, options_for_select([['Monday'], ['Tuesday'],
                        ['Wednesday'],['Thursday'],['Friday'],['Saturday'],['Sunday']])) %>
          <%= select_hour(Time.now) %> Minutos
          <%= select_minute(Time.now) %></br></br>
          Segunda opción
          <%= select_tag(:schedule, options_for_select([['Monday'], ['Tuesday'],
                        ['Wednesday'],['Thursday'],['Friday'],['Saturday'],['Sunday']])) %>
          at <%= select_hour(Time.now) %> hours
          <%= select_minute(Time.now) %> minutes</br></br>
          Tercera opción
          <%= select_tag(:schedule, options_for_select([['Monday'], ['Tuesday'],
                        ['Wednesday'],['Thursday'],['Friday'],['Saturday'],['Sunday']])) %>
          <%= select_hour(Time.now) %> Minutos
          <%= select_minute(Time.now) %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :recommendation %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :recommendation, class: "form-control", placeholder: "How did you hear about us?", autofocus:true %>
        </div>
      </div>
        <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :code %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :code, class: "form-control", placeholder: "Do you have a recommendation code?", autofocus:true %>
        </div>
      </div>
      
      
      
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4 center">
       [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">
      <%= pluralize(obj.errors.count, "Error") %> prohibited this article from beign saved!
    </h4>
      <p>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </p>
      <hr>
      <p class="mb-0">If you need help send us an email to <a href="hello@5roots.co" target="_blank">hello@5roots.co</a></p>
  </div>
<% end %>  
 

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='form'>
  <div class='col-xs-12'>
    <%= form_for(@user,:html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :username %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your E-mail" %>
        </div>
      </div>
       <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-10">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10  col-sm-offset-2">
          <%= f.submit @user.new_record? ? "Sign up" : "Update account", class:"btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4 center">
       [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1><br/>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All 5 Roots Bloggers</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <div class="card" style="width: 18rem; margin-top:15px;">
      <div class="card-body">
        <h5 class="card-title"><%= link_to gravatar_for(user), user_path(user) %></h5>
        <p class="card-text"><%= link_to user.username, user_path(user) %></p>
        <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
        <% if logged_in? and current_user.admin? %></br>
        <%= link_to "Delete this user", user_path(user), method: :delete, 
            data: {confirm: "Are you sure you want to delete this user and all his articles?"} %>
        <% end %>
      </div>
    </div>
<% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for 5 Roots</h1><br/>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class= 'center'><br/>
    <%= gravatar_for @user, size:120  %>
</div><br>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user.articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>